// provide a list of 50 surreal artist in a javascript array

const artist = [
  "Salvador Dali",
  "Rene Magritte",
  "Max Ernst",
  "Joan Miro",
  "Pablo Picasso",
  "Wassily Kandinsky",
  "Piet Mondrian",
  "Mark Rothko",
  "Jackson Pollock",
  "Cy Twombly",
  "Andy Warhol",
  "Roy Lichtenstein",
  "James Turrell",
  "Robert Rauschenberg",
  "Yoko Ono",
  "John Cage",
  "Marcel Duchamp",
  "Francis Bacon",
  "Lucian Freud",
  "Diego Rivera",
  "Frida Kahlo",
  "Rufino Tamayo",
  "David Alfaro Siqueiros",
  "Jose Clemente Orozco",
  "Georgia O'Keeffe",
  "Edward Hopper",
  "Andrew Wyeth",
  "Jasper Johns",
  "Glenn Ligon",
  "Kara Walker",
  "Barbara Kruger",
  "Louise Bourgeois",
  "Richard Serra",
  "John Baldessari",
  "Cindy Sherman",
  "Jeff Koons",
  "Damien Hirst",
  "Rachel Whiteread",
  "Tracy Emin",
  "Gilbert & George",
];

export const commonChoiceMap = {
  artist: artist,
};
